/*!
   \class CameraWidget
   \inherits QWidget
   \brief The CameraWidget class is a custom widget which displays stereoscopic visual data obtained from shared memory.

   \ingroup voltron
   \ingroup vstereo

   This widget contains a \l StereoMemory child widget, which displays the \l QImage frames generated by \StereoMemory using data from shared memory.
   This widget creates and manages its child widgets automatically upon construction of the widget.

   \sa StereoThread, StereoMemory
*/

#include "CameraWidget.h"

/*!
 * Constructs a Stereo widget. Creates the \l QLabel and \l StereoMemory child widgets and establishes their layout within the CameraWidget widget.
 */
CameraWidget::CameraWidget(QWidget *parent) : QWidget(parent)
{
    CameraWidget::title = new QLabel(this);
    title->setText("Camera View");
    title->setSizePolicy(QSizePolicy::Maximum, QSizePolicy::Minimum);

    CameraWidget::display = new CameraRenderer(this);
    display->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
    display->setDisplayType(CameraRenderer::DisplayType::STEREO);

    CameraWidget::typeSelector = new QComboBox(this);
    typeSelector->setSizePolicy(QSizePolicy::Maximum, QSizePolicy::Maximum);
    typeSelector->addItem("Stereo", QString::number(CameraRenderer::DisplayType::STEREO));
    typeSelector->addItem("Depth", QString::number(CameraRenderer::DisplayType::DEPTH));
    typeSelector->setCurrentIndex(CameraRenderer::DisplayType::STEREO);

    QFont font;
    font.setPointSize(font.pointSize() + 4);
    typeSelector->setFont(font);

    QHBoxLayout* hLayout = new QHBoxLayout();
    hLayout->setAlignment(Qt::AlignLeft);
    hLayout->addWidget(title);
    hLayout->addWidget(typeSelector);

    QVBoxLayout* layout = new QVBoxLayout();
    layout->addLayout(hLayout);
    layout->addWidget(display);
    setLayout(layout);

    connect(typeSelector, SIGNAL(currentIndexChanged(const QString&)), this, SLOT(onTypeChanged()));
}

void CameraWidget::onTypeChanged()
{
    display->setDisplayType(typeSelector->currentIndex());
}
