#ifndef PIPES_H
#define PIPES_H

#define READ_WRITE_OWNER (S_IRUSR | S_IWUSR | S_IXUSR)
#define READ_WRITE_GROUP (S_IRGRP | S_IWGRP | S_IXGRP)
#define READ_WRITE_OTHER (S_IROTH | S_IWOTH | S_IXOTH)

#define READ_WRITE_ALL (READ_WRITE_OWNER | READ_WRITE_GROUP | READ_WRITE_OTHER)

#endif
